# Generated by Django 5.1.2 on 2024-11-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_profile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
