# Generated by Django 5.1.2 on 2024-10-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_campaign_profile_current_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_picture',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_pictures/'),
        ),
    ]
